[project]
name = "deepsearch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai-agents",
    "openai",
    "python-dotenv",
    "faiss-cpu",
    "rich",
    "asyncio",
    "aiohttp",
    "fastapi>=0.116.1",
]
